GCP_PROJECT_ID: ecommerce-behavior-381716
KAGGLE_DATASET_PATH: 'mkechinov/ecommerce-events-history-in-cosmetics-shop'
PREFECT_BLOCKNAME_GCP_BUCKET: 'gcp-bucket'
PREFECT_BLOCKNAME_GCP_CREDENTIALS: "gcp-credentials"
PREFECT_BLOCKNAME_DOCKER: "docker"
GCP_BUCKETNAME: "ecommerce_ecommerce-behavior-381716"
GCP_BIGQUERY_DATASET: "ecommerce"
PREFECT_BLOCKNAME_GITHUB: "ecommerce_behavior"
GITHUB_REPO_PATH: "https://github.com/fluentnumbers/ecommerce_behavior"